apiVersion: v2
dependencies:
- name: eric-oss-assurance-indexer
  repository: https://arm.seli.gic.ericsson.se/artifactory/proj-eric-oss-drop-helm
  version: 1.46.0-1
- condition: eric-log-shipper.enabled
  import-values:
  - child: logShipper.config
    parent: global.logShipper.config
  name: eric-log-shipper
  repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-gs-all-helm/
  version: 15.1.0+28
description: Integration chart for Ericsson Assurance Indexer Application
name: eric-assurance-indexer
version: 1.1.0-41
